language: ruby
rvm:
  - 2.3.1
  - 2.4.0

sudo: required

branches:
  only:
    - master

addons:
  postgresql: '9.4'

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_install:
  - gem update --system
  - gem --version

before_script:
  - psql -c 'create database trombonne_test;' -U postgres
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn

script:
  - bundle exec rspec --format doc

notifications:
  slack: h5-bp-e15:OlSkNfaOTVeMtMUZwyhGbiAN
