language: ruby
rvm:
  - 2.3.1
  - 2.4.0

branches:
  only:
    - master

addons:
  postgresql: '9.4'

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - gem update --system
  - gem --version

before_script:
  - psql -c 'create database trombonne_test;' -U postgres

script:
  - bundle exec rails db:schema:load
  - bundle exec rspec --format doc

notifications:
  slack: h5-bp-e15:OlSkNfaOTVeMtMUZwyhGbiAN
