language: ruby
rvm:
  - 2.3.1

addons:
  postgresql: '9.4'

cache: bundler

before_install:
  - gem update --system
  - gem --version

before_script:
  - psql -c 'create database trombonne_test;' -U postgres

script:
  - bundle exec rails db:setup
  - bundle exec rspec
